version: 2

project_name: txtract

before:
  hooks:
    - go mod tidy

builds:
  - id: txtract
    dir: "."
    main: "."
    binary: txtract
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X go.followtheprocess.codes/txtract/internal/cmd.version={{.Version}}
      - -X go.followtheprocess.codes/txtract/internal/cmd.commit={{.Commit}}
      - -X go.followtheprocess.codes/txtract/internal/cmd.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm64
    goarm:
      - "7"

homebrew_casks:
  - name: txtract
    binary: txtract
    directory: Casks
    description: A CLI to interact with txtar archive files
    homepage: https://github.com/FollowTheProcess/txtract
    commit_author:
      name: Tom Fleet
      email: me@followtheprocess.codes
    repository:
      owner: FollowTheProcess
      name: homebrew-tap
      token: "{{.Env.HOMEBREW_TAP_TOKEN}}"
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/txtract"]
          end

archives:
  - id: txtract
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

sboms:
  - id: txtract
    artifacts: archive
    documents:
      - >-
        {{ .ProjectName }}-
        {{- .Version }}-
        {{- .Os }}-
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ .Arch }}{{ end }}.sbom

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ .Tag }}-dev{{ .ShortCommit }}"

changelog:
  # The changelog is handled by release drafter
  disable: true
